# Generated by Django 3.0.6 on 2020-06-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200605_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'ordering': ['-date'], 'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявления'},
        ),
    ]
