# Generated by Django 3.0.6 on 2020-07-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200708_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Gallery', verbose_name='Галерея'),
            preserve_default=False,
        ),
    ]
