# Generated by Django 3.0.6 on 2020-07-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200718_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Gallery', verbose_name='Галерея'),
        ),
    ]
